[book]
authors = ["The Void Linux Team"]
multilingual = false
src = "src"
title = "Void Linux Handbook"

[output.html]
theme = "src/theme"
git-repository-url = "https://github.com/void-linux/void-docs"
edit-url-template = "https://github.com/void-linux/void-docs/edit/master/{path}"

[output.html.redirect]
"/about-this-handbook.html" = "/about/about-this-handbook.html"
"/config/man.html" = "/config/package-documentation/man.html"

[output.latex]
optional = true

[output.linkcheck]
optional = true
follow-web-links = true
exclude = [ "kernel.org", "ntp.org", "\\.onion", "localhost", "hushan.tech", "userbase.kde.org" ]
